# Generated by Django 5.2.2 on 2025-06-07 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('transmission', models.CharField(max_length=100)),
                ('air_conditioning', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bookings', to=settings.AUTH_USER_MODEL)),
                ('which_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_cars.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_cars.category'),
        ),
    ]
